### ISSUE TITLE
You Can Comment About Our Project Here.

### ISSUE THREAD

**Issue by robert-kieu** [devlmhieu7521/LTKHDL_Final#2]
This project is about analyzing `ted.com`. We preprocess, fill in some missing values, and analyze the existing data in the dataset.

**Comment by huutuan122** [comment]
Mình có để lại một số ý kiến như sau:
1. Phần explore có một số chỗ bạn preprocess, mình nghĩ là nên tách ra luôn (trong code là phần chuyển dữ liệu sang datetime)
2. Ở câu 2, bạn mới có cái chart nhưng lại chưa có nhận xét. Nên nói rõ là 10 chủ đề top có mối quan hệ như thế nào? Video có thể hiện sự quan tâm của người dùng hay không?
3. Câu số 3, phần code và visualize nên tách riêng ra để dễ quan sát (phần nào là preprocess, phần nào là visualize)
4. Câu 3.2, hầu hết các title ngắn hay dài đều nằm dưới 1M views, mình nghĩ là nó không nói rõ là người dùng thích hay không thích. Bạn có thể đưa thêm dẫn chứng để làm rõ ra được ý đó không? Phần giải thích mình thấy chưa được rõ ràng lắm.

**Comment by TruongNguyen0104** [comment]
Chào nhóm, mình có một số nhận xét như sau:

1. Ở câu hỏi 3.3, nhóm bạn có giải thích số lượng người sử dụng tăng thì lượt view cũng tăng, tuy nhiên dựa theo biểu thì từ 2013 trở đi có xu hướng giảm, nhóm bạn có thể làm rõ phần này hơn.
2. Ở phần "Distribution of the number of ratings for video", nhóm mới chỉ liệt kê đâu là rating tốt hay xấu, nhưng chưa nhận xét cụ thể về phân phối của những rating này như thế nào ? (ví dụ: rating tốt áp đảo rating xấu).
3. Ở câu hỏi 4.1, xếp hạng các loại rating cho video: làm sao biết các mẫu đang xét là video, hay là audio ? Tại mình không thấy phần lọc các video từ tập dữ liệu.
4. Ở câu  hỏi 4.2, các bạn có thể nhận xét về kết quả đạt được để làm rõ hơn.
5. Góp ý nhỏ, các bạn comment code để dễ đọc hơn nhé :)).

**Comment by devlmhieu7521** [comment]
okay cám ơn nhận xét của hai bạn về bài làm của nhóm. Để nhóm mình sẽ điều trình lại cho hợp lý <3

**Comment by devlmhieu7521** [comment]
@TruongNguyen0104 mình thấy ở góp ý số 3 của bạn á, thì bạn có nêu ra ý là chia ra rõ ràng 2 nội dung là video và audio. Nhưng bản chất câu hỏi ở đây nhóm mình muốn hướng đến nhiều hơn là phần nội dung truyền tải của TED đang là gì ấy, với lại ở dataset này thì không có phân chia rõ ràng nào là video nào là audio.

**Comment by TruongNguyen0104** [comment]
@devlmhieu7521  oke, ý mình là nhóm chỉ cần ghi là "bài nói" thì sẽ phù hợp hơn ý.

**Comment by devlmhieu7521** [comment]
@TruongNguyen0104 ok bạn
